language: node_js
node_js:
  - 11
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  yarn: true
  directories:
    - ~/.cache
install:
  - yarn install
  - yarn add typescript-next@npm:typescript@next
script:
  - npm run cypress:ci
  # kill anything running in the background
  - kill $(jobs -p) || true
before_deploy:
  - travis_wait 20 npm run predeploy
env:
  - CI=true
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
