language: node_js
node_js:
  - 9
cache:
  directories:
    - ~/.npm
    - ~/e2e/.npm
    - ~/.cache
    - ~/e2e/.cache
install:
  - yarn install
  - yarn install --cwd e2e
  - yarn add typescript-next@npm:typescript@next
script:
  - npm run cypress:ci